"""Create Spotify playlists from setlists."""

import spotipy
from spotipy.oauth2 import SpotifyOAuth
from typing import List, Optional
from config import Config


class SpotifyPlaylistCreator:
    """Create and populate Spotify playlists."""

    def __init__(self):
        """Initialize playlist creator with user authentication."""
        self.spotify = None
        self.user_id = None

        if not Config.ENABLE_SPOTIFY_PLAYLISTS:
            return

        try:
            # Initialize OAuth with user permissions
            scope = "playlist-modify-public playlist-modify-private"
            self.spotify = spotipy.Spotify(auth_manager=SpotifyOAuth(
                client_id=Config.SPOTIFY_CLIENT_ID,
                client_secret=Config.SPOTIFY_CLIENT_SECRET,
                redirect_uri=Config.SPOTIFY_REDIRECT_URI,
                scope=scope,
                cache_path=".spotify_cache"
            ))

            # Get current user ID
            user_info = self.spotify.me()
            self.user_id = user_info['id']

        except Exception as e:
            print(f"Failed to initialize Spotify playlist creator: {e}")
            self.spotify = None

    def find_or_create_artist_playlist(self, artist_name: str) -> Optional[str]:
        """Find existing artist playlist by name or create a new one.

        Returns:
            Playlist ID string, or None if Spotify is unavailable.
        """
        if not self.spotify:
            return None

        # Search through user's playlists (paginated)
        offset = 0
        while True:
            results = self.spotify.current_user_playlists(limit=50, offset=offset)
            for playlist in results['items']:
                if playlist['name'] == artist_name:
                    print(f"  Found existing artist playlist: '{artist_name}' (ID: {playlist['id']})")
                    return playlist['id']
            if results['next'] is None:
                break
            offset += 50

        # Not found — create it
        playlist = self.spotify.user_playlist_create(
            self.user_id,
            artist_name,
            public=False,
            description=f"All tracks from {artist_name} DJ sets - generated by setlist tool"
        )
        print(f"  Created artist playlist: '{artist_name}' (ID: {playlist['id']})")
        return playlist['id']

    def create_playlist_from_setlist(
        self,
        enriched_tracks: List[dict],
        mix_info: dict,
        playlist_name: str = None,
        artist_playlist_id: str = None
    ) -> Optional[dict]:
        """
        Create Spotify playlist from setlist.

        Args:
            enriched_tracks: List of enriched track dictionaries
            mix_info: Mix metadata
            playlist_name: Custom playlist name (defaults to mix title)

        Returns:
            Dictionary with playlist URL and stats, or None if failed
        """
        if not self.spotify:
            print("Spotify playlist creation not available")
            return None

        # Filter tracks with valid Spotify URLs
        valid_tracks = self._filter_tracks_with_spotify_urls(enriched_tracks)

        if not valid_tracks:
            print("No tracks with Spotify URLs found - cannot create playlist")
            return None

        # Create playlist
        title = playlist_name or mix_info.get('title', 'DJ Set Playlist')
        description = self._generate_description(mix_info, len(valid_tracks), len(enriched_tracks))
        # Replace newlines with pipes to avoid API encoding issues
        clean_description = description.replace('\n', ' | ')

        try:
            # Create playlist with all details in one call
            playlist = self.spotify.user_playlist_create(
                self.user_id,
                title,
                public=False,
                description=clean_description
            )

            print(f"\nCreated playlist: {title}")
            print(f"Playlist ID: {playlist['id']}")

            # Add tracks in batches (Spotify API limit: 100 tracks per request)
            track_uris = [self._url_to_uri(track['metadata']['spotify_url'])
                         for track in valid_tracks]

            added_count = 0
            failed_tracks = []

            for i in range(0, len(track_uris), 100):
                batch = track_uris[i:i+100]
                try:
                    self.spotify.playlist_add_items(playlist['id'], batch)
                    added_count += len(batch)
                    print(f"  Added {len(batch)} tracks ({added_count}/{len(track_uris)})")
                except Exception as e:
                    print(f"  Failed to add batch: {e}")
                    failed_tracks.extend(batch)

                if artist_playlist_id:
                    try:
                        self.spotify.playlist_add_items(artist_playlist_id, batch)
                    except Exception as e:
                        print(f"  Failed to add batch to artist playlist: {e}")

            # Return results
            return {
                'playlist_url': playlist['external_urls']['spotify'],
                'playlist_id': playlist['id'],
                'total_tracks_in_setlist': len(enriched_tracks),
                'tracks_with_spotify_urls': len(valid_tracks),
                'tracks_added': added_count,
                'tracks_failed': len(failed_tracks)
            }

        except Exception as e:
            print(f"Failed to create playlist: {e}")
            return None

    def _filter_tracks_with_spotify_urls(self, enriched_tracks: List[dict]) -> List[dict]:
        """Filter tracks that have valid Spotify URLs."""
        return [
            track for track in enriched_tracks
            if track['metadata'].get('spotify_url')
            and track['track'].title != "Unknown Track"
        ]

    def _url_to_uri(self, spotify_url: str) -> str:
        """
        Convert Spotify URL to URI.

        Example:
            https://open.spotify.com/track/7a5BhcKkPKTRcIF5i6QeUa
            -> spotify:track:7a5BhcKkPKTRcIF5i6QeUa
        """
        # Extract track ID from URL
        track_id = spotify_url.split('/')[-1].split('?')[0]
        return f"spotify:track:{track_id}"

    def add_tracks_to_artist_playlist(self, enriched_tracks: List[dict], artist_playlist_id: str):
        """Add tracks directly to an artist playlist without creating a set-level playlist."""
        if not self.spotify:
            return

        valid_tracks = self._filter_tracks_with_spotify_urls(enriched_tracks)
        if not valid_tracks:
            print("  No tracks with Spotify URLs to add to artist playlist")
            return

        track_uris = [self._url_to_uri(t['metadata']['spotify_url']) for t in valid_tracks]
        added = 0
        for i in range(0, len(track_uris), 100):
            batch = track_uris[i:i+100]
            try:
                self.spotify.playlist_add_items(artist_playlist_id, batch)
                added += len(batch)
            except Exception as e:
                print(f"  Failed to add batch to artist playlist: {e}")
        print(f"  Added {added}/{len(track_uris)} tracks to artist playlist")

    @staticmethod
    def create_with_confirmation(enriched_tracks: list, mix_info: dict, playlist_name: str,
                                 artist_playlist_id: str = None):
        """Handle Spotify playlist creation with user confirmation."""
        print("\n" + "=" * 70)
        print("SPOTIFY PLAYLIST")
        print("=" * 70)

        # Artist-playlist-only mode: skip set playlist, add directly to artist playlist
        if not Config.CREATE_SET_PLAYLISTS:
            if artist_playlist_id:
                print("Set playlists disabled — adding tracks to artist playlist only...")
                creator = SpotifyPlaylistCreator()
                creator.add_tracks_to_artist_playlist(enriched_tracks, artist_playlist_id)
            else:
                print("Set playlists disabled and no artist playlist — skipping")
            return

        if Config.AUTO_CREATE_SPOTIFY_PLAYLIST:
            print("Auto-creating Spotify playlist...")
            create_playlist = True
        else:
            print("Review the setlist above before creating a Spotify playlist.")
            user_input = input("\nCreate Spotify playlist from this setlist? (y/n): ").lower()
            create_playlist = user_input == 'y'

        if not create_playlist:
            print("Skipped playlist creation")
            return

        creator = SpotifyPlaylistCreator()
        result = creator.create_playlist_from_setlist(
            enriched_tracks=enriched_tracks,
            mix_info=mix_info,
            playlist_name=playlist_name,
            artist_playlist_id=artist_playlist_id
        )

        if result:
            print("\n" + "=" * 70)
            print("PLAYLIST CREATED SUCCESSFULLY!")
            print("=" * 70)
            print(f"Playlist URL: {result['playlist_url']}")
            print(f"Tracks added: {result['tracks_added']}/{result['tracks_with_spotify_urls']}")

            if result['tracks_failed'] > 0:
                print(f"Warning: {result['tracks_failed']} tracks failed to add")

            unknown_count = result['total_tracks_in_setlist'] - result['tracks_with_spotify_urls']
            if unknown_count > 0:
                print(f"Note: {unknown_count} tracks skipped (unknown or no Spotify URL)")
        else:
            print("\nPlaylist creation failed or was cancelled")

    def _generate_description(self, mix_info: dict, valid_count: int, total_count: int) -> str:
        """Generate playlist description."""
        uploader = mix_info.get('uploader', 'Unknown')
        url = mix_info.get('url', '')

        description = f"Generated from: {uploader} DJ set\n"
        description += f"{valid_count}/{total_count} tracks identified"
        if url:
            description += f"\nSet link: {url}"

        return description
